// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzi6s3rpW13C8LXiNGkk9ELBD1wK_4Nek',
    appId: '1:181423307229:web:5c00b95ff225be94b1de34',
    messagingSenderId: '181423307229',
    projectId: 'returnsuccess4',
    authDomain: 'returnsuccess4.firebaseapp.com',
    storageBucket: 'returnsuccess4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-mJtcPvuZzieAe5WzOccJwDGcnylsxaE',
    appId: '1:181423307229:android:919319831ffaa9cdb1de34',
    messagingSenderId: '181423307229',
    projectId: 'returnsuccess4',
    storageBucket: 'returnsuccess4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK_EWa73wzGR-Gv2oHFaaeMubIPKcBe8k',
    appId: '1:181423307229:ios:2f3056a1e9ba2ab7b1de34',
    messagingSenderId: '181423307229',
    projectId: 'returnsuccess4',
    storageBucket: 'returnsuccess4.appspot.com',
    iosClientId: '181423307229-fmg04apfl8jl820l1pev439n49sv9fgo.apps.googleusercontent.com',
    iosBundleId: 'com.returnsuccess.app',
  );
}
